default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("DB_POOL") { 32 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  checkout_timeout: 5

development:
  <<: *default
  database: auth_api_development

test:
  <<: *default
  database: auth_api_test

production:
  <<: *default
  database: auth_api_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
